blank_issues_enabled: false
contact_links:
  - name: Retro Engine Modding Server
    url: https://dc.railgun.works/retroengine
    about: If you have any questions about the decompilation or want help with modding, ask here.
  - name: The Nexus/EggBanana123
    url: https://discordapp.com/users/1171891080317390971
    about: Contact the lead developer of Nexus Restored and Sonic Nexplus for questions about them specifically.
